variables:
  CI_DOCKERHUB_IMAGE: huncrys/epg

include:
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/kaniko-build@~latest
  - component: $CI_SERVER_FQDN/oaklab/ci-templates/manifest-tool-manifest@~latest
